call SALESPROFITDATE("01/01/2018","30/01/2018");
-- =========================================================================================================================
-- specific date
/*
SELECT
  PRODUCTS.REFERENCE,
  PRODUCTS.NAME,
  DATE_FORMAT(RECEIPTS.DATENEW, "%d/%m/%Y") AS TDATE,
  '00:00:00' AS TTIME,-- DATE_FORMAT(RECEIPTS.DATENEW,"%h:%i:%s %p") AS TTIME,
  PRODUCTS.PRICEBUY,
  PRODUCTS.PRICESELL,
  SUM(TICKETLINES.UNITS) AS SOLD_UNITS,
  SUM(TICKETLINES.UNITS * PRODUCTS.PRICEBUY) AS COST_VALUE,
  SUM(TICKETLINES.UNITS * PRODUCTS.PRICESELL) AS EXPECTED_SALES_VALUE,
  SUM(TICKETLINES.PRICE * TICKETLINES.UNITS) AS ACTUAL_SALES_VALUE,
  (SUM(TICKETLINES.UNITS * PRODUCTS.PRICESELL)
  - SUM(TICKETLINES.UNITS * PRODUCTS.PRICEBUY)) AS EXPECTED_PROFIT,
  (SUM(TICKETLINES.PRICE * TICKETLINES.UNITS) - SUM(TICKETLINES.UNITS * PRODUCTS.PRICEBUY)) AS ACTUAL_PROFIT
FROM TICKETLINES -- TICKETLINES 
INNER JOIN products ON products.ID = ticketlines.PRODUCT
INNER JOIN receipts ON receipts.ID = ticketlines.TICKET
INNER JOIN tickets ON TICKETS.ID = ticketlines.TICKET AND TICKETS.TICKETTYPE=0
where ticketlines.ticket in (select receipts.id from receipts where DATE_FORMAT(RECEIPTS.DATENEW, "%d/%m/%Y")='01/02/2018') 
-- and ticketlines.product='8709da74-5e71-4d8d-b91b-0cf299103222'
GROUP BY TICKETLINES.PRODUCT -- ,STOCKDIARY.DATENEW      
ORDER BY DATE_FORMAT(RECEIPTS.DATENEW, "%d/%m/%Y"),PRODUCTS.NAME ASC;
 */
-- =========================================================================================================================
-- no date
/*
  SELECT
  PRODUCTS.REFERENCE,
  PRODUCTS.NAME,
  DATE_FORMAT(RECEIPTS.DATENEW, "%d/%m/%Y") AS TDATE,
  '00:00:00' AS TTIME, -- DATE_FORMAT(RECEIPTS.DATENEW,"%h:%i:%s %p") AS TTIME,
  PRODUCTS.PRICEBUY,
  PRODUCTS.PRICESELL,
  SUM(TICKETLINES.UNITS) AS SOLD_UNITS,
  SUM(TICKETLINES.UNITS * PRODUCTS.PRICEBUY) AS COST_VALUE,
  SUM(TICKETLINES.UNITS * PRODUCTS.PRICESELL) AS EXPECTED_SALES_VALUE,
  SUM(TICKETLINES.PRICE * TICKETLINES.UNITS) AS ACTUAL_SALES_VALUE,
  (SUM(TICKETLINES.UNITS * PRODUCTS.PRICESELL)
  - SUM(TICKETLINES.UNITS * PRODUCTS.PRICEBUY)) AS EXPECTED_PROFIT,
  (SUM(TICKETLINES.PRICE * TICKETLINES.UNITS) - SUM(TICKETLINES.UNITS * PRODUCTS.PRICEBUY)) AS ACTUAL_PROFIT
FROM TICKETLINES -- TICKETLINES 
INNER JOIN products ON products.ID = ticketlines.PRODUCT
INNER JOIN receipts ON receipts.ID = ticketlines.TICKET
INNER JOIN tickets ON TICKETS.ID = ticketlines.TICKET AND TICKETS.TICKETTYPE=0
where ticketlines.ticket in (select receipts.id from receipts) -- where DATE_FORMAT(RECEIPTS.DATENEW, "%d/%m/%Y")=in_DATE1) 
-- and ticketlines.product='8709da74-5e71-4d8d-b91b-0cf299103222'
GROUP BY DATE_FORMAT(RECEIPTS.DATENEW, "%d/%m/%Y"),TICKETLINES.PRODUCT -- ,STOCKDIARY.DATENEW      
ORDER BY RECEIPTS.DATENEW,PRODUCTS.NAME ASC;
  */
-- =========================================================================================================================
-- date range
/*
  SELECT
  PRODUCTS.REFERENCE,
  PRODUCTS.NAME,
  DATE_FORMAT(RECEIPTS.DATENEW, "%d/%m/%Y") AS TDATE,
  '00:00:00' AS TTIME, -- DATE_FORMAT(RECEIPTS.DATENEW,"%h:%i:%s %p") AS TTIME,
  PRODUCTS.PRICEBUY,
  PRODUCTS.PRICESELL,
  SUM(TICKETLINES.UNITS) AS SOLD_UNITS,
  SUM(TICKETLINES.UNITS * PRODUCTS.PRICEBUY) AS COST_VALUE,
  SUM(TICKETLINES.UNITS * PRODUCTS.PRICESELL) AS EXPECTED_SALES_VALUE,
  SUM(TICKETLINES.PRICE * TICKETLINES.UNITS) AS ACTUAL_SALES_VALUE,
  (SUM(TICKETLINES.UNITS * PRODUCTS.PRICESELL)
  - SUM(TICKETLINES.UNITS * PRODUCTS.PRICEBUY)) AS EXPECTED_PROFIT,
  (SUM(TICKETLINES.PRICE * TICKETLINES.UNITS) - SUM(TICKETLINES.UNITS * PRODUCTS.PRICEBUY)) AS ACTUAL_PROFIT
FROM TICKETLINES -- TICKETLINES 
INNER JOIN products ON products.ID = ticketlines.PRODUCT
INNER JOIN receipts ON receipts.ID = ticketlines.TICKET
INNER JOIN tickets ON TICKETS.ID = ticketlines.TICKET AND TICKETS.TICKETTYPE=0
where ticketlines.ticket in 
    (select receipts.id from receipts 
    WHERE receipts.DATENEW BETWEEN STR_TO_DATE("01/02/2018", '%d/%m/%Y') AND DATE_ADD(STR_TO_DATE("02/02/2018", '%d/%m/%Y'),INTERVAL 1 DAY)) 
-- and ticketlines.product='8709da74-5e71-4d8d-b91b-0cf299103222'
GROUP BY DATE_FORMAT(RECEIPTS.DATENEW, "%d/%m/%Y"),TICKETLINES.PRODUCT  
ORDER BY RECEIPTS.DATENEW,PRODUCTS.NAME ASC;
 */
-- =========================================================================================================================
--  select STR_TO_DATE('02/02/2018', '%d/%m/%Y')