/*specific month*/
-- /*
SELECT
  DATE_FORMAT(RECEIPTS.DATENEW, "%M/%Y") AS TDATE,
  SUM(TICKETLINES.UNITS * PRODUCTS.PRICEBUY) AS COST_VALUE,
  SUM(TICKETLINES.UNITS * PRODUCTS.PRICESELL) AS EXPECTED_SALES_VALUE,
  SUM(TICKETLINES.PRICE * TICKETLINES.UNITS) AS ACTUAL_SALES_VALUE,
  (SUM(TICKETLINES.UNITS * PRODUCTS.PRICESELL) - SUM(TICKETLINES.UNITS * PRODUCTS.PRICEBUY)) AS EXPECTED_PROFIT,
  (SUM(TICKETLINES.PRICE * TICKETLINES.UNITS) - SUM(TICKETLINES.UNITS * PRODUCTS.PRICEBUY)) AS ACTUAL_PROFIT
FROM TICKETLINES TICKETLINES
 INNER JOIN receipts ON receipts.ID = ticketlines.TICKET 
  AND DATE_FORMAT(receipts.DATENEW,"%Y-%m") = DATE_FORMAT(STR_TO_DATE("01/02/2018", '%d/%m/%Y'),"%Y-%m") 
 INNER JOIN products ON products.ID = TICKETLINES.PRODUCT
  INNER JOIN tickets on TICKETLINES.TICKET = tickets.ID and tickets.TICKETTYPE=0
GROUP BY YEAR(receipts.DATENEW),MONTH(receipts.DATENEW)
ORDER BY YEAR(receipts.DATENEW),MONTH(receipts.DATENEW);

-- */
-- ========================================================================================================================================
/* No date */
-- /*
SELECT
  DATE_FORMAT(RECEIPTS.DATENEW, "%M/%Y") AS TDATE,
  SUM(TICKETLINES.UNITS * PRODUCTS.PRICEBUY) AS COST_VALUE,
  SUM(TICKETLINES.UNITS * PRODUCTS.PRICESELL) AS EXPECTED_SALES_VALUE,
  SUM(TICKETLINES.PRICE * TICKETLINES.UNITS) AS ACTUAL_SALES_VALUE,
  (SUM(TICKETLINES.UNITS * PRODUCTS.PRICESELL) - SUM(TICKETLINES.UNITS * PRODUCTS.PRICEBUY)) AS EXPECTED_PROFIT,
  (SUM(TICKETLINES.PRICE * TICKETLINES.UNITS) - SUM(TICKETLINES.UNITS * PRODUCTS.PRICEBUY)) AS ACTUAL_PROFIT
FROM TICKETLINES TICKETLINES
 INNER JOIN receipts ON receipts.ID = ticketlines.TICKET 
 INNER JOIN products ON products.ID = TICKETLINES.PRODUCT
  INNER JOIN tickets on TICKETLINES.TICKET = tickets.ID and tickets.TICKETTYPE=0
GROUP BY YEAR(receipts.DATENEW),MONTH(receipts.DATENEW)
ORDER BY YEAR(receipts.DATENEW),MONTH(receipts.DATENEW);
 -- */
-- ========================================================================================================================================
/* date range */
-- /*
SELECT
  DATE_FORMAT(RECEIPTS.DATENEW, "%M/%Y") AS TDATE,
  SUM(TICKETLINES.UNITS * PRODUCTS.PRICEBUY) AS COST_VALUE,
  SUM(TICKETLINES.UNITS * PRODUCTS.PRICESELL) AS EXPECTED_SALES_VALUE,
  SUM(TICKETLINES.PRICE * TICKETLINES.UNITS) AS ACTUAL_SALES_VALUE,
  (SUM(TICKETLINES.UNITS * PRODUCTS.PRICESELL) - SUM(TICKETLINES.UNITS * PRODUCTS.PRICEBUY)) AS EXPECTED_PROFIT,
  (SUM(TICKETLINES.PRICE * TICKETLINES.UNITS) - SUM(TICKETLINES.UNITS * PRODUCTS.PRICEBUY)) AS ACTUAL_PROFIT
FROM TICKETLINES TICKETLINES
 INNER JOIN receipts ON receipts.ID = ticketlines.TICKET 
  AND DATE_FORMAT(receipts.DATENEW,"%Y-%m") BETWEEN DATE_FORMAT(STR_TO_DATE("01/01/2018", '%d/%m/%Y'),"%Y-%m") 
  AND DATE_FORMAT(STR_TO_DATE("02/03/2018", '%d/%m/%Y'),"%Y-%m")
 INNER JOIN products ON products.ID = TICKETLINES.PRODUCT
  INNER JOIN tickets on TICKETLINES.TICKET = tickets.ID and tickets.TICKETTYPE=0
GROUP BY YEAR(receipts.DATENEW),MONTH(receipts.DATENEW)
ORDER BY YEAR(receipts.DATENEW),MONTH(receipts.DATENEW);
--  */
-- ========================================================================================================================================