DELIMITER $$
DROP PROCEDURE IF EXISTS `TEST`$$
CREATE PROCEDURE `TEST`()
BEGIN
  SET @OUT1 = 'TEST THIS OUTPUT';
  SET @OUT2 = ' SECOND LINE';
  SELECT CONCAT(@OUT1,@OUT2);
END$$
DELIMITER ;


CALL TEST();

DROP PROCEDURE IF EXISTS TEST;