-- CALL UPLOADPROD('1234','1234','NEW TEST 01',200,100,'ThisCat','000',1000);
/*
DELIMITER $$
DROP PROCEDURE IF EXISTS UPLOADPROD$$
CREATE PROCEDURE UPLOADPROD(IN in_REF VARCHAR(255),in_CODE VARCHAR(255),in_NAME VARCHAR(255),in_PRICEBUY DOUBLE,
  in_PRICESELL DOUBLE,in_CATNAME VARCHAR(255),in_TAXCAT VARCHAR(255),in_UNITS DOUBLE)
BEGIN

  INSERT IGNORE INTO categories (ID,NAME) values (convert(uuid(),char),in_CATNAME);

SELECT ID INTO @CATID FROM categories WHERE categories.NAME = in_CATNAME;
-- select @CATID;

SET @DISP = concat('<html>',in_NAME);

insert into products (ID,REFERENCE,CODE,NAME,PRICEBUY,PRICESELL,CATEGORY,TAXCAT,DISPLAY,ALIAS,ISCATALOG)
  VALUES (CONVERT(UUID(),CHAR),in_REF,in_CODE,in_NAME,in_PRICESELL,in_PRICEBUY,@CATID,in_TAXCAT,@DISP,in_NAME,1);
  
SELECT ID into @ProdID from products where products.CODE=in_CODE;

REPLACE into stockcurrent (LOCATION,PRODUCT,UNITS)
  VALUES (0,@ProdID,in_UNITS);

END$$
DELIMITER ;
*/

 